# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88de8c8fa13a7b7073b02f7e4d043e5c82cb126c615f25f59d1b8f340f59bb3efdc20fc176771d1739b2bd951199f0a447b4b4c9bec4b62071e1fa78e0073cd6

test:
  secret_key_base: ccd8508ff5a34109bafb2b51b66b88f4b2cc2e329acc998538aa025f2ea6d9d6a0b650ac62bd0e9b989bd21d7388deee04bfdc94d745ad13ce6e302e694ef9e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
